base/urls.py
from django.contrib import admin
from django.urls import path, include
from api.models import ProductResource, LessonResource
from tastypie.api import Api

api = Api(api_name='v1')
lesson_recource = LessonResource()
product_recource = ProductResource()
api.register(lesson_recource)
api.register(product_recource)


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('product.urls')),
    path('api/', include(api.urls))
]

product/urls.py
from django.urls import path
from . import views

app_name = 'product'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:lesson_id>', views.single_lesson, name='single_lesson')
]

api/models.py
from tastypie.resources import ModelResource
from product.models import Product, Lesson
from .authentication import CustomAuthentication
from tastypie.authentication import Authentication


class ProductResource(ModelResource):
    class Meta:
        queryset = Product.objects.all()
        resource_name = 'products'
        allowed_methods = ['get']


class LessonResource(ModelResource):
    class Meta:
        queryset = Lesson.objects.all()
        recource_name = 'lessons'
        allowed_methods = ['get', 'post', 'delete']
        authentication = CustomAuthentication()
        authorization = Authentication()

product/models.py
from django.db import models
from django.utils import timezone


class Product(models.Model):
    title = models.CharField(max_length=255)
    owner = models.CharField(max_length=255)
    creared_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.title


class Lesson(models.Model):
    title = models.CharField(max_length=255)
    url_path = models.TextField(default='')
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    owner = models.CharField(max_length=255)
    during_veiw = models.IntegerField()

    def __str__(self):
        return self.title


class User(models.Model):
    username = models.CharField(
        unique=True,
        max_length=50,
        verbose_name='Nikname',
        help_text='Enter your niknmae'
    )
    first_name = models.CharField(
        max_length=50,
        verbose_name='Имя',
        help_text='Введите имя',
    )
    last_name = models.CharField(
        max_length=50,
        verbose_name='Фамилия',
        help_text='Введите фамилию',
    )
    email = models.EmailField(
        max_length=50,
        blank=False,
        unique=True,
        verbose_name='Адрес электронной почты',
        help_text='Укажите адрес электронной почты',
    )

    class Meta:
        ordering = ('username',)
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self) -> str:
        return self.username


class LessonView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    lesson = models.ForeignKey(Lesson, on_delete=models.CASCADE)
    time_view = models.DateTimeField(default=timezone.now)
    status_view = models.BooleanField(default=False)
    viewed_duration = models.IntegerField(default=0)

    def save(self, *args, **kwargs):
        if self.viewed_duration >= (self.lesson.during_veiw * 0.8):
            self.status = True
        else:
            self.status = False
        super().save(*args, **kwargs)

    def __str__(self) -> str:
        return self.user

product/views.py
from django.shortcuts import render, get_object_or_404
from .models import Lesson, Product, LessonView


def index(request):
    lessons = Lesson.objects.all()
    products = Product.objects.all()
    return render(request, 'product/lessons.html', {'lessons': lessons, 'products': products})


def single_lesson(request, lesson_id):
    lesson = get_object_or_404(Lesson, pk=lesson_id)
    lesson_views = LessonView.objects.filter(lesson_id=lesson_id)
    return render(request, 'product/single_lesson.html', {'lesson': lesson, 'lesson_views': lesson_views})

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous" />
  <title>{% block title %}{% endblock title %}</title>
</head>

<body>
  <nav class="navbar navbar-dark bg-dark">
    <div class="container">
      <a href={% url "product:index" %} class="navbar-brand"> List Product</a>
      <span class="navbar-text">
        <a href="/admin/" class="me-2" target="_blank">Admin</a>
        <a href="/api/v1/" target="_blank">API</a>
      </span>
    </div>
  </nav>
  <main class="container">{% block content %} {% endblock %}</main>
</body>

</html>

templates/product/lessons.html
{% extends 'base.html' %}

{% block title %}List Product{% endblock title %}

{%block content %}
<table class="table mt-5 table-bordered table-strited table-hover">
  <thead class="table-dark">
    <tr>
      <th>Название продукта</th>
      <th>Название урока</th>
      <th>Владелец продукта</th>
      <th>Ссылка на урок</th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    {% for lesson in lessons %}
    <tr>
      <td>{{ lesson.product }}</td>
      <td>{{ lesson.title }}</td>
      <td>{{ lesson.owner }}</td>
      <td><a href={% url "product:single_lesson" lesson.id %}>Просмотр видео урока</a></td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% endblock content %}

templates/product/single_lesson.html
{% extends 'base.html' %}

{% block title %}{{ lesson.title }}{% endblock %}

{% block content %}

<h1 class="mt-5"> {{lesson.product}}</h1>
<p>Название урока: {{lesson.title}}</p>
<p>Видео: <iframe width="560"
									height="315"
									src={{lesson.url_path}}
									title="YouTube video player" 
									frameborder="0" 
									allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" 
									allowfullscreen></iframe></p>
<p>Длительность просмотра видео в сек.: {{lesson.during_veiw}}</p>
<p>Статус просмотра: {{lesson.lesson_views}}</p>

{% endblock %}